# Профиль: маркетплейс-дайджест
profile: marketplace

paths:
  data_dir: ./data
  logs_dir: ./logs
  sessions_dir: ./sessions

telegram:
  session_name: ./sessions/marketplace/session

publication:
  channel: '@rnpozwb'
  footer_template: |
    _____________________________________
    Подпишись, чтобы быть в курсе: https://t.me/rnpozwb
  header_template: "📌 Главные новости маркетплейсов за {date}"

listener:
  mode: subscriptions
  min_message_length: 50
  channel_whitelist: []
  channel_blacklist:
    - spamads
  manual_channels: []

filters:
  exclude_keywords:
    - реклама
    - курс
    - промокод
    - обучение платное

processor:
  schedule_time: '09:00'
  timezone: Europe/Moscow
  duplicate_threshold: 0.85
  top_n: 15
  exclude_count: 5

# 3-категорийная система для дайджеста маркетплейсов
categories:
  - name: ozon
    display_name: Ozon
    enabled: true
    target_channel: '@rnpozwb'
    keywords:
      - ozon
      - озон
      - ozon seller
    exclude_keywords:
      - реклама
      - курс
      - промокод
      - обучение платное

  - name: wildberries
    display_name: Wildberries
    enabled: true
    target_channel: '@rnpozwb'
    keywords:
      - wildberries
      - вайлдберриз
      - вб
      - wb
      - wildberries seller
    exclude_keywords:
      - реклама
      - курс
      - промокод
      - обучение платное

  - name: general
    display_name: Общее
    enabled: true
    target_channel: '@rnpozwb'
    keywords:
      - маркетплейс
      - marketplace
      - электронная торговля
      - ecommerce
      - селлер
      - seller
      - яндекс маркет
      - yandex market
      - авито
      - avito
      - закон
      - налог
      - ФНС
      - минторг
    exclude_keywords:
      - реклама
      - курс
      - промокод
      - обучение платное

channels:
  all_digest:
    enabled: true
    target_channel: '@rnpozwb'
    category_counts:
      ozon: 7          # 7 новостей про Ozon (после дедупликации ~5-6)
      wildberries: 7   # 7 новостей про Wildberries (после дедупликации ~5-6)
      general: 4       # 4 новости про другие маркетплейсы/законы/е-торговлю (после дедупликации ~3)

moderation:
  enabled: true
  timeout_hours: 2

cleanup:
  raw_messages_days: 14
  published_days: 60
  run_weekly: true

status:
  enabled: true
  chat: '@SoftStatustnb'
  bot_name: Marketplace News Bot
  interval_minutes: 30
  bot_token: '8293385906:AAFzdn_kWnSVVrPRoYADRzpr9HQooFQyKgQ'
  timezone: Europe/Moscow

logging:
  file: ./logs/marketplace/bot.log

database:
  path: ./data/marketplace_news.db
